### ISSUE TITLE
create a linseedObject from data matrix

### ISSUE THREAD

**Issue by tdw1221** [ctlab/LinSeed#6]
Hi,
    I was trying to create a linseedObject with a data matrix, however, the tutorial only provides way to create an object from GEO database. Is there a way i could make one myself?

Thanks
daiwei

**Comment by konsolerr** [comment]
Hi daiwei,

you can certainly do that, please see #1 
in short, you can just pass the matrix object instead of GEO identifier and after that you'll be able to follow the tutorial.

I will soon move from R6 classes to S4 classes and this will hopefully make documentation of methods/functions a bit easier and more transparent.

Cheers,
Kostya

**Comment by tdw1221** [comment]
Thank you Kostya!
